version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=winter
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - APP_KEY=base64:Prf5s5k3FeIUaTQzs1E7LZVH2Zfe6vziag3jDlQCu0o=
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=winter
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
      

volumes:
  mysql_data:
